{
    "name": "Customer Base",
    "version": "19.0.1.0.0",
    "author": "dynapps",
    "website": "https://www.dynapps.eu",
    "category": "Hidden",
    "license": "LGPL-3",
    "depends": [
        "account",
        "account_asset",
        "account_intrastat",
        "account_reports",
        "analytic",
        "auditlog",
        "base",
        "l10n_it_asset_management",
        "dyn_analytics",
        "dyn_block_uninstall",
        "dyn_export_settings",
        "dyn_healthcheck",
        "mail",
        "purchase",
        "server_environment_ir_config_parameter",
        "sign",
        "web_environment_ribbon",
        "web_studio",
    ],
    "data": [
        "data/auditlog_rule_data.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "dyn_required": True,
}
