{
    "name": "DynApps Dashboard",
    "category": "Hidden",
    "version": "19.0.1.0.0",
    "author": "dynapps",
    "license": "AGPL-3",
    "website": "https://www.dynapps.eu",
    "depends": ["base", "web", "mail", "account"],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "views/export_import_wizard.xml",
        "views/dyn_dashboard_views.xml",
        "views/validation_pattern_views.xml",
        "data/dyn_database.xml",
        "data/xx.dashboard.validation.patterns.csv",
        "data/ir_cron.xml",
    ],
    "demo": [
        "demo/dashboard_demo.xml",
        "demo/dashboard_demo_query_fields.xml",
        "demo/demo_dashboard_drilling.xml",
        "demo/dashboard_dates_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dyn_dashboard/static/lib/js/xlsx.full.min.js",
            "dyn_dashboard/static/lib/js/jspdf.umd.min.js",
            "dyn_dashboard/static/lib/js/jspdf.plugin.autotable.min.js",
            "web/static/lib/luxon/luxon.js",
            "web/static/lib/jquery/jquery.js",
            "dyn_dashboard/static/lib/js/moment.min.js",
            "dyn_dashboard/static/lib/js/daterangepicker.js",
            "dyn_dashboard/static/lib/css/daterangepicker.css",
            "dyn_dashboard/static/lib/css/jquery.dsmorse-gridster.min.css",
            "dyn_dashboard/static/lib/css/tabulator.min.css",
            "dyn_dashboard/static/src/css/dyn_dashboard.css",
            "dyn_dashboard/static/src/css/gridstack.scss",
            "dyn_dashboard/static/lib/js/apexcharts.min.js",
            "dyn_dashboard/static/lib/js/gridstack.js",
            "dyn_dashboard/static/src/xml/dyn_dashboard_templates.xml",
            "dyn_dashboard/static/src/js/dyn_dashboard_parser.esm.js",
            "dyn_dashboard/static/src/js/dyn_dashboard_renderer.esm.js",
            "dyn_dashboard/static/src/js/dyn_dashboard_view.esm.js",
            "dyn_dashboard/static/src/js/dyn_dashboard_model.esm.js",
            "dyn_dashboard/static/src/js/dyn_dashboard_controller.esm.js",
            "dyn_dashboard/static/src/xml/dyn_dashboard_templates.xml",
            "dyn_dashboard/static/src/xml/dyn_dashboard_renderer.xml",
            "dyn_dashboard/static/lib/js/select2/select2.js",
            "dyn_dashboard/static/lib/js/select2/select2.css",
        ],
        "web.assets_qweb": [],
        "dyn_dashboard.jsLibs": [
            "/dyn_dashboard/static/lib/js/gridstack.js",
            "/dyn_dashboard/static/lib/js/apexcharts.min.js",
            "/dyn_dashboard/static/lib/js/tabulator.min.js",
        ],
    },
    "external_dependencies": {
        "python": [
            "arrow",
            "pandas",
        ],
    },
    "installable": True,
    "application": True,
}
# Part of Odoo. See LICENSE file for full copyright and licensing details.
